version: '3.8'
services:
  flask:
    build: .
    container_name: flask-SQLALCHEMY
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: 'mariadb-SQLALCHEMY'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./data:/var/lib/myslq
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'Phpmyadmin-SQLALCHEMY'
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    ports:
      - '8000:80'